### ISSUE TITLE
Why are the other issues opened under issues? I'm confused. 

### ISSUE THREAD

**Issue by d-m-u** [insaka/insaka#150]
If they're images, the rest of the images are in public/images, and they should all go there. I'm not sure why you have issues opened that're pictures.

**Comment by insaka** [comment]
I totally agree. I know how to upload them, but for the life of me, I can't figure out how to move them to the image folder

**Comment by insaka** [comment]
If you open an issue and put in an image, the boox will display the URL of that image which is what I use to link to that image in the code

**Comment by d-m-u** [comment]
So if you clone the code with the clone url -- from terminal it's like ```git clone [URL from github]``` you get a local copy of the project. Then you can cd into the directory of the project, checkout a branch with ```git checkout -b [name of branch]``` and then you can put the images into wherever you want them there. That's local, so you can see that that worked by running a ```rails s``` and looking at localhost:3000 in browser. If that's how it should look, you can do a ```git push origin [name of git branch]```, open the PR, and merge it.

**Comment by insaka** [comment]
I'm going to pretend that i understand that. I have figured out how to add files properly now. At some undetermined point in the future I will go back and organize them all. Have you ever run Google page insights?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
