### ISSUE TITLE
web tab text may be wrong

### ISSUE THREAD

**Issue by d-m-u** [insaka/insaka#191]
can't look at it right this second but i think you want "insaka" to be tab text rather than the names of the individual pages?

**Comment by insaka** [comment]
I'm not sure what you mean

**Comment by d-m-u** [comment]
![screen shot 2017-12-20 at 7 35 30 am](https://user-images.githubusercontent.com/16326669/34207429-661b0264-e558-11e7-89ea-46b1d43f4496.png)

**Comment by d-m-u** [comment]
I would think that's supposed to say just Insaka, but I dunno anything.

**Comment by insaka** [comment]
Feel free to change it
