### ISSUE TITLE
anyone else think it's weird the index page buttons are different colors?

### ISSUE THREAD

**Issue by d-m-u** [insaka/insaka#194]
![screen shot 2017-12-17 at 10 24 21 am](https://user-images.githubusercontent.com/16326669/34080981-9082bef2-e314-11e7-9cfe-f2ff4ffe6d73.png)

**Comment by insaka** [comment]
Yes, feel free to fix it. I have 15,000 words due on Jan 9th so I can't get to to it for a bit
