### ISSUE TITLE
code comments are nice

### ISSUE THREAD

**Issue by d-m-u** [insaka/insaka#211]
"We will begin accepting applications shortly, and hope to have chosen several girls by July 1st.
In the meantime, you can donate to our general fund." That's great, but it would've been nice if you'd commented out the code you removed so I had something to go on to see it for updating the db. It's real useful to use comments so we're not just taking stuff out but also to tell me what you did.

**Comment by insaka** [comment]
Will do. I saved all the code from the donate page. It's in a text doc on the google drive page. How do you comment out something?

**Comment by insaka** [comment]
Ok, I figured out how to do comments, and I put the code back. It's down at the bottom of the donate page
