### ISSUE TITLE
styles mostly don't belong in views

### ISSUE THREAD

**Issue by d-m-u** [insaka/insaka#225]
https://github.com/insaka/insaka/commit/7c7836a19e19532ce7f8cdddce601a4377071f4b#diff-68ffa7236b277ceb77d0ce2d4557bf4dR67 It's better if we keep the stuff you're putting in the style tag in the css files rather than directly in the view code.

**Comment by insaka** [comment]
Feel free to change it, I don't know how. I put "orange" into the CSS. Ithought that was all there was to it
