### ISSUE TITLE
More link should take you to girl you clicked on

### ISSUE THREAD

**Issue by d-m-u** [insaka/insaka#247]
Clicking on the link should take you to the page with the girl you clicked on at the top of the page, not just the top of the page. It's called an anchor, and you can see the way to do it here: https://stackoverflow.com/questions/757891/how-to-create-an-anchor-and-redirect-to-this-specific-anchor-in-ruby-on-rails

**Comment by insaka** [comment]
I would love to do this, but my thesis is due in 17 days and I need to get that done. Feel free to do the anchors if you want, but I just don't have time right now
