### ISSUE TITLE
The more page text is weird

### ISSUE THREAD

**Issue by d-m-u** [insaka/insaka#252]
It'd be nice to have some idea of who Brooke Cutlan, Precious Katowa, Stephanie Salazar, and Bailey Wright are. It just reads weird without any explanation of how they know the girls they're nominating.

**Comment by d-m-u** [comment]
Also we use the pronoun "she" too many times and it'd be nice if we used the girls names more, especially in the first couple sentences.

**Comment by insaka** [comment]
Mom is in charge of that and I have passed on your comments
